### ISSUE TITLE
module not maintained?

### ISSUE THREAD

**Issue by xini** [xini/silverstripe-soapserver#7]
Since this was once core functionality it would be nice if the module was maintained by the core committers. For example, this module is missing a composer.json (see pull request #2). 
Any chance we get this up to scratch again? Thanks.

**Comment by chillu** [comment]
@CezaryH @bhongong @jelicanin @bilekt3 @xini @Zauberfisch @selay @adrianlogue You have all expressed interest in the `silverstripe-soapserver` module in the last years (by github stars, watches, forks or issues). SilverStripe Ltd. no longer has the resources to maintain this module (we have over 50 modules against our name). If you are interested in keeping the module alive, please agree on a new maintainer with each other and fork the repo under your own github account. We're happy to transfer ownership at this point. 

/cc @sminnee @dhensby @camfindlay

**Comment by xini** [comment]
Hi guys,
If no one else is interested in this, I'm happy to offer my help. 
Cheers, Flo

**Comment by sminnee** [comment]
That would be appreciated, @xini.

**Comment by sminnee** [comment]
@xini if it makes sense to you, shall we transfer this to github.com/xini/silverstripe-soapserver? We might put something in the readme like "originally developed by SilverStripe Ltd, now maintained by Florian Thoma"?

**Comment by xini** [comment]
Hi @sminnee. sure. how do we do that?

**Comment by sminnee** [comment]
OK @xini I've invited you to be an admin of this module. Once you accept the invite, you should be able to delete your fork of this module, and then go into the settings section, and use the Transfer function to move it to github.com/xini/silverstripe-soapserver.

Because of the changed maintenance requirements, I would suggest adding this to Packagist as `xini/silverstripe-soapserver` or `innoweb/silverstripe-soapserver`, rather than `silverstripe/soapserver`.

Thanks,
Sam

**Comment by xini** [comment]
Thanks @sminnee. I'll try. 
Would you rgenerally recommend renaming my github account to 'innoweb' to keep everything consistent? Do you have experience with changing user names on github?

**Comment by sminnee** [comment]
> Would you rgenerally recommend renaming my github account to 'innoweb' to keep everything consistent?

If you're going to take that approach I would suggest that you create an innoweb organisation (it's free for public repositories). This means that if you want to include other teammates at Innoweb, you can do so.

Both options are valid, it depends on whether maintenance responsibility rests with you as an individual, or with your company. For example, I have a few modules that I host on sminnee, because they are more personal projects.

**Comment by dhensby** [comment]
The name of your github account and the "vendor" name in packagist are unrelated, so it's not too important

**Comment by xini** [comment]
I have trasfered the module. Thanks everyone for your help.

**Comment by xini** [comment]
@sminnee one more question: do you want me to keep the SS licence or replace it with MIT?
